### ISSUE TITLE
change `${__from:date:YYMMDD}` to `${__to:date:YYMMDD}`

### ISSUE THREAD

**Issue by wetterfrosch** [SaintPatrick86/TrainDashboard#1]
In Panel "Abfahrtsmonitr", querying /apis/timetables with

`https://apis.deutschebahn.com/db-api-marketplace/apis/timetables/v1/plan/${StationEva}/${__from:date:YYMMDD}/${__to:date:HH}`

... this does not work between midnight and 6am --- unless you change "__from" to "__to" in the particular API-call. 

After midnight passes: hour is correct, but when calendar-date changes, the date of the beginning of the dashboard time-range (now-6h) is called, so DB-API doesn't give a response for the current hour of yesterday's date.

but great stuff! :) really like it, didn't heard about infinity-datasource for now

**Comment by patrickmoch** [comment]
Thanks for the Issue :+1: , changed the part of URL to ${__to:date:YYMMDD}
